database:
    image: mysql:5.7
    ports:
        - "33061:3306"
    command: --init-file /Assignment4_212405108/.github/workflows/Script.sql
    volumes:
        - ./Assignment4_212405108/.github/workflows/Script.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: Sibongile@TUT14
        MYSQL_DATABASE: myDatabase
        MYSQL_USER: root
        MYSQL_PASSWORD: Sibongile@TUT14
